[build]
  command = "npm run build"
  functions = "functions"

[dev]
  framework = "#custom"
  functions = "functions"
  command = "npm run dev"
  targetPort = 8080
  publish = "dist"

[context.develop.environment]
  BULLE = "kaka"